update tardy and secsock dependencies to fix a CI error
```elvish
Run zig build
D:\a\zzz\zzz\build.zig.zon:8:20: error: unable to unpack packfile
            .url = "git+https://github.com/tardy-org/tardy?ref=main#1436624746f06f34ebb3a49fe8a931af8b316fbe",
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
note: unable to create file 'src\runtime\timer.zig': PathAlreadyExists
Error: Process completed with exit code 1.
```

with the latest tardy, examples can be built without the error
    `undefined symbol: tardy_swap_frame` when `.use_llvm = true`
    isn't set, becuase tardy no longer uses global assembly for
    its context switching. This localizes the `.use_llvm` to only
    tardy

Also `.link_libc` isn't needed for the examples anymore

Signed-off-by: Bernard Assan <mega.alpha100@gmail.com>